### ISSUE TITLE
Proton 5.13 and up fail

### ISSUE THREAD

**Issue by tony4212** [hectorm/docker-steam#1]
When testing steam games proton doesn't work for anything 5.13 and up. 
Not sure if anyone else has this issue.
I know that proton 5.13 and up uses steam runtime soldier and it is know to cause issues.
Tried variety of games known to work with 5.13 or greater. All games refuse to open.

Tried proton logs, but they don't give any output. Also uninstalled steam and installed it from apt. 
Tried installing proton-ge with same result. 
Only thing that kind of works was using [proton-caller](https://github.com/caverym/proton-caller)

**Comment by hectorm** [comment]
Steam Runtime 2 (Soldier) uses [Bubblewrap](https://github.com/containers/bubblewrap) to run games in a container. It's necessary to specify the `--security-opt seccomp=unconfined` option to allow Bubblewrap to run inside Docker.

I've tried running VVVVVV with Proton 6.3 and it worked without issues after doing this.

![](https://user-images.githubusercontent.com/852266/147863910-7f64ef00-b2ea-4a1e-87a7-c247d08314aa.png)

**Comment by tony4212** [comment]
That worked perfectly. Thanks
