### ISSUE TITLE
Controller issues with steam link app & remote play

### ISSUE THREAD

**Issue by tony4212** [hectorm/docker-steam#2]
Currently only able to test this with a steam controller.
When using remote play or steam link app the controller fails to work properly in most games. 
Using the controller as a mouse works fine, but as soon as the game launches it fails to properly detect a controller in game settings. 
List of things that failed to work:

- Adding uinput into docker container via  `--device /dev/uinput/:/dev/uinput`
  - Following these two instructions to get read and write working for uinput: 
  https://steamcommunity.com/app/221410/discussions/0/523897277912430760/
  https://steamcommunity.com/app/353370/discussions/2/1735465524711324558/?ctp=35
  Controller shows up as Microsoft X-Box 360 pad (`cat /proc/bus/input/devices` and `dmesg`)

  - Installing steam-devices (everything below ran without steam-devices installed)
  - Disabled and enabled steam input & steam overlay
  - Installed [sc-controller](https://github.com/kozec/sc-controller)

- Add `--privileged` to docker container without uinput read and write
  Controller did **not** show up in `cat /proc/bus/input/devices` and `dmesg`
  - Allow read and write for uinput via `chmod +666 /dev/uinput`
  Controller shows up as Microsoft X-Box 360 pad (`cat /proc/bus/input/devices` and `dmesg`)
  According to Session Stats steam is recognizing it as a steam controller.

In most cases steam shows that a gamepad configuration is being used when the game is running, but nothing on the controller will work.

**Comment by hectorm** [comment]
I have tried a Steam Controller and a Switch Pro Controller and I wasn't able to get it to work either.

My use case for this image is to use Steam Link to run games inside the container.

**Comment by tony4212** [comment]
Without making any changes some games will work. Shadow of the Tomb Raider is the only game that works with the controller. Other games you need to change the controller to bind to the keyboard and mouse. I had to do this for Rise of the Tomb Raider. 

I am not entirely sure why it is having that problem. I know Shadow of the Tomb Raider has a built in "Steam Input" setting.  The one solution I haven't tried is installing steam through wine. However, it isn't an ideal solution.

**Comment by tony4212** [comment]
Apparently someone has found a solution. 
https://forums.unraid.net/topic/118390-support-josh5-steam-headless/page/3/
https://github.com/Josh5/docker-steam-headless

I managed to get their docker container up and running. I haven't been able to fully test it since several games keep on crashing. However, it does appear that controllers work with remote play. You might be able to implement what they did into this container.

**Comment by hectorm** [comment]
Thank you for those links.

I have added to the base image the udevd service and configured some udev rules in this image.

Now when starting the container in privileged mode the Steam Controller is recognized by jstest-gtk. Unfortunately when I start Steam the controller stops being recognized and only works correctly in Big Picture and games that support the Steam Input API.

I will keep testing.

![](https://user-images.githubusercontent.com/852266/149828034-d15a1e9f-51e5-4a3b-b569-8eabd14b33e1.png)

**Comment by tony4212** [comment]
This worked when using remote play. Even for games without Steam Input API. 

However, I also tried with your v19 again. That also seemed to work with when privileged mode. So I am not sure something on my system changed or if steam updated? Although on v19 I needed to add `chmod +666 /dev/uinput`

Also have you tried installing steam-devices alongside steam?

**Comment by hectorm** [comment]
The main change in the latest version is that udev is now correctly configured and it's no longer necessary to chmod `/dev/uinput` for the controller to work.

In my case what I'm trying to do is to get the controller to work while running the game through an RDP connection instead of using remote play. If in your case it's working it's possible that my problem is related to the RDP connection itself, maybe the game gets confused when recognizing the keyboard and mouse of the RDP connection apart from the controller.

Regarding installing the `steam-devices` package, it's not necessary since that package provides the udev rules for the controllers. Those same udev rules are already included in the official Steam deb package, which is the one I'm installing.

If you confirm that your use case has been resolved without any additional changes to the image I will consider this issue solved.

**Comment by tony4212** [comment]
As far as I can tell it resolve the problem for remote play.

**Comment by hectorm** [comment]
Thank you very much for your time, I really appreciate it.
